add income and income-methods
devkevin8/expenses-principal-backend pull request #5
Opened 2024-09-25 22:08 UTC by soyjuanjoyque

add new features (income and income-methods)

2024-09-25 22:37 UTC, R3lativ3 requested changes

2024-09-25 22:37 UTC, R3lativ3 commented on src/bd/connection.ts
> +  //Agregar Outcomes
when adding a comment for something that needs to be done in the future please add: TODO:

2024-09-25 22:37 UTC, R3lativ3 commented on src/entityBase/base.entity.ts
> +    this.createdAt = new Date(currentDate.getTime() - 6 * 60 * 60 * 1000);
duplicated code, please add just a single definition to avoid duplication

2024-09-25 22:37 UTC, R3lativ3 commented on src/entityBase/base.entity.ts
> +    const currentDate = new Date();
please add a tab after the function initialization. Consider add an extension to avoid this kind of stuff, Prettier, or some linter

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income-methods/income-methods.controller.ts
> +      status: HttpStatus.CREATED,
normalize the response, to avoid difference between all the controllers, if we are going to use this type, we need to create a new interface like this: 
interface response {
   status: HttpStatus,
   message: string,
   data: any
}

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income-methods/income-methods.controller.ts
> +    if(isNaN(userId)) {
add error response with the new structure
and also add try catch on controller level

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income-methods/income-methods.service.ts
> +      throw new Error('User ID is not a number');
validations should be in the controller

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income-methods/income-methods.service.ts
> +      throw new Error('User ID is not a number');
remove this if

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income-methods/income-methods.service.ts
> +    await this.incomeMethodRepository.update(id, { deleted: true, deletedBy: userId });
avoid two calls at the database for the same purpose, update a value.
there should be one single update call.
    await this.incomeMethodRepository.update(id, { deleted: true, deletedBy: userId, deletedAt: new Date().now });

2024-09-25 22:37 UTC, R3lativ3 commented on src/features/income/entities/income.entity.ts
> +import {Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, DeleteDateColumn, ManyToOne} from "typeorm";
when there is a lot of imports, consider using something like this:
import {
a,
b
c,
d,
e
} from 'url'

2024-09-27 03:31 UTC, soyjuanjoyque commented on src/features/income-methods/income-methods.controller.ts
> +      status: HttpStatus.CREATED,
interface created in src>common>interfaces>response.interface.ts and has the following structure to avoid the message (Http status is enough)
{
  -status: HttpStatus,
  -data: any
}

2024-09-27 03:31 UTC, soyjuanjoyque commented on src/features/income-methods/income-methods.controller.ts
> +    if(isNaN(userId)) {
try catch added

2024-09-27 03:33 UTC, soyjuanjoyque commented on src/features/income-methods/income-methods.service.ts
> +      throw new Error('User ID is not a number');
'if' was removed and avoid the data validation,translated to controller and  just logic in the service

2024-09-27 03:34 UTC, soyjuanjoyque commented on src/entityBase/base.entity.ts
> +    this.createdAt = new Date(currentDate.getTime() - 6 * 60 * 60 * 1000);
private getUTCTimeMinusSix() function created in base.entity to avoid the duplicated code

2024-09-27 03:34 UTC, soyjuanjoyque commented on src/bd/connection.ts
> +  //Agregar Outcomes
//TODO: added

2024-09-28 18:34 UTC, R3lativ3 approved these changes
now the code is more legible, thanks for that
and also great use of the service, remember that you can re use your method to find something in the controller before to send it to update, to avoid that search call in the service. Good work.

2024-09-28 18:34 UTC, merged